### ISSUE TITLE
How to run/deploy the project, please need documentation.

### ISSUE THREAD

**Issue by jamilxt** [TheChance101/beep-beep#627]
It would be helpful to have a guideline on running the application, and setting up the environment. 

Thank you.

**Comment by AzizaHelmy** [comment]
@jamilxt 
for the mobile apps, there is no additional setup to can run them, you can run any app directly without adding any thing in the environment till now as we deployed our work on a remote server.
for the desktop app, plz follow this issue https://github.com/TheChance101/beep-beep/issues/542
to can login use this accounts: 
======
for resturant:
username: theChance_res
password: 12345678aA@
====
for delivery:
username: theChance_delivery
password: 12345678aA@
====
for dashboard admin:
username: theChance_admin
password: 12345678aA@
====
and so on

also check this issue :
https://github.com/TheChance101/beep-beep/issues/551#issuecomment-1798531053
and let me know if your problem is solved
Thanks :)

**Comment by RaheemJnr** [comment]
Whenever I try to log in to the admin dashboard using the credentials you provided, I keep getting "No internet connection error"
